import { Booking } from '../types/booking'
import { getBookings, saveBookings } from './db'

// Seed Future Mock Data (June - Dec 2026) for testing
export async function seedFutureMockData(): Promise<number> {
  const futureBookings: Booking[] = [
    {
      id: 'mock-june-1',
      room_id: 'room-2',
      guest_name: 'Gabriel Reyes',
      guest_email: 'gabriel.reyes@gmail.com',
      guest_phone: '0917-222-3344',
      check_in: '2026-06-10',
      check_out: '2026-06-14',
      source: 'website',
      status: 'confirmed',
      downpayment_paid: 1900,
      balance_due: 2400,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-june-2',
      room_id: 'room-6',
      guest_name: 'Sofia Dimagiba',
      guest_email: 'sofia@dimagiba.org',
      guest_phone: '0918-333-4455',
      check_in: '2026-06-18',
      check_out: '2026-06-20',
      source: 'airbnb',
      status: 'confirmed',
      downpayment_paid: 1800,
      balance_due: 2300,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-june-3',
      venue_id: 'venue-gazebo',
      guest_name: 'Clara Cruz',
      guest_email: 'clara.cruz@yahoo.com',
      guest_phone: '0919-444-5566',
      check_in: '2026-06-25',
      check_out: '2026-06-26',
      source: 'manual',
      status: 'confirmed',
      downpayment_paid: 2500,
      balance_due: 3000,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-1',
      room_id: 'room-1',
      guest_name: 'Ramon Magsaysay',
      guest_email: 'ramon@magsaysay.ph',
      guest_phone: '0920-555-6677',
      check_in: '2026-07-05',
      check_out: '2026-07-09',
      source: 'booking_com',
      status: 'confirmed',
      downpayment_paid: 2100,
      balance_due: 2600,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-2',
      room_id: 'room-8',
      guest_name: 'Alfonso Sy',
      guest_email: 'alfonso@sygroup.com.ph',
      guest_phone: '0921-666-7788',
      check_in: '2026-07-15',
      check_out: '2026-07-18',
      source: 'google_maps',
      status: 'confirmed',
      downpayment_paid: 1275,
      balance_due: 1775,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-3',
      room_id: 'room-1',
      guest_name: 'Juan Luna',
      guest_email: 'juan.luna@spoliarium.ph',
      guest_phone: '0917-111-2222',
      check_in: '2026-07-12',
      check_out: '2026-07-16',
      source: 'facebook',
      status: 'confirmed',
      downpayment_paid: 2100,
      balance_due: 2600,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-4',
      room_id: 'room-1',
      guest_name: 'Andres Bonifacio',
      guest_email: 'andres@katipunan.org',
      guest_phone: '0917-222-3333',
      check_in: '2026-07-20',
      check_out: '2026-07-25',
      source: 'website',
      status: 'confirmed',
      downpayment_paid: 2625,
      balance_due: 3125,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-5',
      room_id: 'room-2',
      guest_name: 'Emilio Aguinaldo',
      guest_email: 'emilio@kawit.gov.ph',
      guest_phone: '0917-333-4444',
      check_in: '2026-07-01',
      check_out: '2026-07-06',
      source: 'airbnb',
      status: 'confirmed',
      downpayment_paid: 2375,
      balance_due: 2875,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-6',
      room_id: 'room-2',
      guest_name: 'Apolinario Mabini',
      guest_email: 'apolinario@sublime.ph',
      guest_phone: '0917-444-5555',
      check_in: '2026-07-10',
      check_out: '2026-07-15',
      source: 'manual',
      status: 'confirmed',
      downpayment_paid: 2375,
      balance_due: 2875,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-7',
      room_id: 'room-2',
      guest_name: 'Melchora Aquino',
      guest_email: 'tandangsora@balintawak.org',
      guest_phone: '0917-555-6666',
      check_in: '2026-07-18',
      check_out: '2026-07-24',
      source: 'booking_com',
      status: 'confirmed',
      downpayment_paid: 2850,
      balance_due: 3350,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-8',
      room_id: 'room-2',
      guest_name: 'Gregoria de Jesus',
      guest_email: 'gregoria@lakambini.ph',
      guest_phone: '0917-666-7777',
      check_in: '2026-07-26',
      check_out: '2026-07-30',
      source: 'website',
      status: 'confirmed',
      downpayment_paid: 1900,
      balance_due: 2400,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-9',
      room_id: 'room-3',
      guest_name: 'Marcelo H. del Pilar',
      guest_email: 'plaridel@solidaridad.es',
      guest_phone: '0917-777-8888',
      check_in: '2026-07-03',
      check_out: '2026-07-08',
      source: 'website',
      status: 'confirmed',
      downpayment_paid: 2375,
      balance_due: 2875,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-10',
      room_id: 'room-3',
      guest_name: 'Graciano Lopez Jaena',
      guest_email: 'graciano@solidaridad.es',
      guest_phone: '0917-888-9999',
      check_in: '2026-07-12',
      check_out: '2026-07-17',
      source: 'airbnb',
      status: 'confirmed',
      downpayment_paid: 2375,
      balance_due: 2875,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-11',
      room_id: 'room-3',
      guest_name: 'Antonio Luna',
      guest_email: 'general.luna@artillery.ph',
      guest_phone: '0917-999-0000',
      check_in: '2026-07-20',
      check_out: '2026-07-26',
      source: 'booking_com',
      status: 'confirmed',
      downpayment_paid: 2850,
      balance_due: 3350,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-12',
      room_id: 'room-4',
      guest_name: 'Jose Abad Santos',
      guest_email: 'jose.abadsantos@judiciary.gov',
      guest_phone: '0918-111-2222',
      check_in: '2026-07-02',
      check_out: '2026-07-07',
      source: 'manual',
      status: 'confirmed',
      downpayment_paid: 2375,
      balance_due: 2875,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-13',
      room_id: 'room-4',
      guest_name: 'Gabriela Silang',
      guest_email: 'gabriela@silang.org',
      guest_phone: '0918-222-3333',
      check_in: '2026-07-12',
      check_out: '2026-07-16',
      source: 'facebook',
      status: 'confirmed',
      downpayment_paid: 1900,
      balance_due: 2400,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-14',
      room_id: 'room-4',
      guest_name: 'Diego Silang',
      guest_email: 'diego@silang.org',
      guest_phone: '0918-333-4444',
      check_in: '2026-07-22',
      check_out: '2026-07-28',
      source: 'airbnb',
      status: 'confirmed',
      downpayment_paid: 2850,
      balance_due: 3350,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-15',
      room_id: 'room-5',
      guest_name: 'Macario Sakay',
      guest_email: 'macario@sakay.org',
      guest_phone: '0918-444-5555',
      check_in: '2026-07-04',
      check_out: '2026-07-10',
      source: 'booking_com',
      status: 'confirmed',
      downpayment_paid: 3600,
      balance_due: 4100,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-16',
      room_id: 'room-5',
      guest_name: 'Artemio Ricarte',
      guest_email: 'artemio@ricarte.ph',
      guest_phone: '0918-555-6666',
      check_in: '2026-07-14',
      check_out: '2026-07-20',
      source: 'website',
      status: 'confirmed',
      downpayment_paid: 3600,
      balance_due: 4100,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-17',
      room_id: 'room-5',
      guest_name: 'Teresa Magbanua',
      guest_email: 'teresa@magbanua.org',
      guest_phone: '0918-666-7777',
      check_in: '2026-07-24',
      check_out: '2026-07-29',
      source: 'manual',
      status: 'confirmed',
      downpayment_paid: 3000,
      balance_due: 3500,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-18',
      room_id: 'room-6',
      guest_name: 'Francisco Balagtas',
      guest_email: 'francisco@balagtas.ph',
      guest_phone: '0918-777-8888',
      check_in: '2026-07-01',
      check_out: '2026-07-06',
      source: 'website',
      status: 'confirmed',
      downpayment_paid: 4500,
      balance_due: 5000,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-19',
      room_id: 'room-6',
      guest_name: 'Jose Palma',
      guest_email: 'jose@palma.ph',
      guest_phone: '0918-888-9999',
      check_in: '2026-07-10',
      check_out: '2026-07-15',
      source: 'facebook',
      status: 'confirmed',
      downpayment_paid: 4500,
      balance_due: 5000,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-20',
      room_id: 'room-6',
      guest_name: 'Julian Felipe',
      guest_email: 'julian@felipe.ph',
      guest_phone: '0918-999-0000',
      check_in: '2026-07-20',
      check_out: '2026-07-25',
      source: 'google_maps',
      status: 'confirmed',
      downpayment_paid: 4500,
      balance_due: 5000,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-21',
      room_id: 'room-7',
      guest_name: 'Josefa Llanes Escoda',
      guest_email: 'josefa@girlscouts.ph',
      guest_phone: '0919-111-2222',
      check_in: '2026-07-05',
      check_out: '2026-07-10',
      source: 'airbnb',
      status: 'confirmed',
      downpayment_paid: 2750,
      balance_due: 3250,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-22',
      room_id: 'room-7',
      guest_name: 'Gliceria de Villavicencio',
      guest_email: 'gliceria@patriot.ph',
      guest_phone: '0919-222-3333',
      check_in: '2026-07-15',
      check_out: '2026-07-20',
      source: 'website',
      status: 'confirmed',
      downpayment_paid: 2750,
      balance_due: 3250,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-23',
      room_id: 'room-7',
      guest_name: 'Marina Dizon',
      guest_email: 'marina@dizon.org',
      guest_phone: '0919-333-4444',
      check_in: '2026-07-22',
      check_out: '2026-07-28',
      source: 'manual',
      status: 'confirmed',
      downpayment_paid: 3300,
      balance_due: 3800,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-24',
      room_id: 'room-8',
      guest_name: 'Trinidad Tecson',
      guest_email: 'trinidad@tecson.ph',
      guest_phone: '0919-444-5555',
      check_in: '2026-07-02',
      check_out: '2026-07-07',
      source: 'facebook',
      status: 'confirmed',
      downpayment_paid: 2125,
      balance_due: 2625,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-25',
      room_id: 'room-8',
      guest_name: 'Patrocinio Gamboa',
      guest_email: 'patrocinio@gamboa.org',
      guest_phone: '0919-555-6666',
      check_in: '2026-07-22',
      check_out: '2026-07-27',
      source: 'booking_com',
      status: 'confirmed',
      downpayment_paid: 2125,
      balance_due: 2625,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-26',
      room_id: 'room-9',
      guest_name: 'Galicano Apacible',
      guest_email: 'galicano@apacible.ph',
      guest_phone: '0919-666-7777',
      check_in: '2026-07-06',
      check_out: '2026-07-12',
      source: 'website',
      status: 'confirmed',
      downpayment_paid: 2700,
      balance_due: 3200,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-27',
      room_id: 'room-9',
      guest_name: 'Leon Apacible',
      guest_email: 'leon@apacible.ph',
      guest_phone: '0919-777-8888',
      check_in: '2026-07-16',
      check_out: '2026-07-21',
      source: 'google_maps',
      status: 'confirmed',
      downpayment_paid: 2250,
      balance_due: 2750,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-28',
      room_id: 'room-9',
      guest_name: 'Felipe Agoncillo',
      guest_email: 'felipe@agoncillo.ph',
      guest_phone: '0919-888-9999',
      check_in: '2026-07-24',
      check_out: '2026-07-30',
      source: 'airbnb',
      status: 'confirmed',
      downpayment_paid: 2700,
      balance_due: 3200,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-29',
      room_id: 'room-10',
      guest_name: 'Marcela Agoncillo',
      guest_email: 'marcela@agoncillo.ph',
      guest_phone: '0919-999-0000',
      check_in: '2026-07-04',
      check_out: '2026-07-09',
      source: 'website',
      status: 'confirmed',
      downpayment_paid: 6000,
      balance_due: 6500,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-30',
      room_id: 'room-10',
      guest_name: 'Juan Sumulong',
      guest_email: 'juan@sumulong.ph',
      guest_phone: '0920-111-2222',
      check_in: '2026-07-14',
      check_out: '2026-07-20',
      source: 'manual',
      status: 'confirmed',
      downpayment_paid: 7200,
      balance_due: 7700,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-july-31',
      room_id: 'room-10',
      guest_name: 'Claro M. Recto',
      guest_email: 'claro@recto.org',
      guest_phone: '0920-222-3333',
      check_in: '2026-07-23',
      check_out: '2026-07-28',
      source: 'booking_com',
      status: 'confirmed',
      downpayment_paid: 6000,
      balance_due: 6500,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-aug-1',
      room_id: 'room-3',
      guest_name: 'Maria Leonora',
      guest_email: 'leonora.maria@outlook.com',
      guest_phone: '0922-777-8899',
      check_in: '2026-08-12',
      check_out: '2026-08-15',
      source: 'facebook',
      status: 'confirmed',
      downpayment_paid: 1425,
      balance_due: 1925,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-aug-2',
      room_id: 'room-10',
      guest_name: 'Jose Rizal',
      guest_email: 'rizal.jose@ilustrado.es',
      guest_phone: '0923-888-9900',
      check_in: '2026-08-20',
      check_out: '2026-08-22',
      source: 'website',
      status: 'confirmed',
      downpayment_paid: 2400,
      balance_due: 2900,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-sept-1',
      room_id: 'room-5',
      guest_name: 'Liza Soberano',
      guest_email: 'liza@soberano.com',
      guest_phone: '0924-999-0011',
      check_in: '2026-09-08',
      check_out: '2026-09-12',
      source: 'airbnb',
      status: 'confirmed',
      downpayment_paid: 2400,
      balance_due: 2900,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-sept-2',
      venue_id: 'venue-garden',
      guest_name: 'Pedro Penduko',
      guest_email: 'pedro@penduko.ph',
      guest_phone: '0925-000-1122',
      check_in: '2026-09-18',
      check_out: '2026-09-19',
      source: 'manual',
      status: 'confirmed',
      downpayment_paid: 3750,
      balance_due: 4250,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-oct-1',
      room_id: 'room-7',
      guest_name: 'Catriona Gray',
      guest_email: 'catriona@missuniverse.tv',
      guest_phone: '0926-111-2233',
      check_in: '2026-10-10',
      check_out: '2026-10-13',
      source: 'booking_com',
      status: 'confirmed',
      downpayment_paid: 1650,
      balance_due: 2150,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-oct-2',
      room_id: 'room-4',
      guest_name: 'Manny Pacquiao',
      guest_email: 'manny@pacman.com',
      guest_phone: '0927-222-3344',
      check_in: '2026-10-24',
      check_out: '2026-10-28',
      source: 'website',
      status: 'confirmed',
      downpayment_paid: 1900,
      balance_due: 2400,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-nov-1',
      room_id: 'room-9',
      guest_name: 'Carlos Yulo',
      guest_email: 'carlos@gymnastics.org',
      guest_phone: '0928-333-4455',
      check_in: '2026-11-14',
      check_out: '2026-11-17',
      source: 'facebook',
      status: 'confirmed',
      downpayment_paid: 1350,
      balance_due: 1850,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-nov-2',
      room_id: 'room-2',
      guest_name: 'Kylie Verzosa',
      guest_email: 'kylie@verzosa.com',
      guest_phone: '0929-444-5566',
      check_in: '2026-11-20',
      check_out: '2026-11-23',
      source: 'airbnb',
      status: 'confirmed',
      downpayment_paid: 1425,
      balance_due: 1925,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-dec-1',
      room_id: 'room-5',
      guest_name: 'Pia Wurtzbach',
      guest_email: 'pia.wurtzbach@universe.org',
      guest_phone: '0930-555-6677',
      check_in: '2026-12-12',
      check_out: '2026-12-15',
      source: 'booking_com',
      status: 'confirmed',
      downpayment_paid: 1800,
      balance_due: 2300,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-dec-2',
      room_id: 'room-6',
      guest_name: 'Lea Salonga',
      guest_email: 'lea@salongatheatre.com',
      guest_phone: '0931-666-7788',
      check_in: '2026-12-22',
      check_out: '2026-12-27',
      source: 'website',
      status: 'confirmed',
      downpayment_paid: 4500,
      balance_due: 5000,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    },
    {
      id: 'mock-dec-3',
      venue_id: 'venue-vacation',
      guest_name: 'Vicente Manansala',
      guest_email: 'vicente@manansala.ph',
      guest_phone: '0932-777-8899',
      check_in: '2026-12-24',
      check_out: '2026-12-25',
      source: 'manual',
      status: 'confirmed',
      downpayment_paid: 7500,
      balance_due: 8000,
      security_deposit: 500,
      created_at: new Date().toISOString(),
      expires_at: null
    }
  ]

  const current = await getBookings()
  const currentIds = new Set(current.map(b => b.id))

  const toAdd = futureBookings.filter(b => !currentIds.has(b.id))

  if (toAdd.length > 0) {
    await saveBookings([...current, ...toAdd])
  }

  return toAdd.length
}
